### ISSUE TITLE
The OSD icon has not changed at all

### ISSUE THREAD

**Issue by lida2003** [OpenIPC/silicon_research#53]
Hardware:
- Arducopter 4.5.6
- OpenIPC SSC338Q+IMX415 master+94d0b84, 2024-06-20
- Ground Station: Hi3536 master+5f03f03, 2024-03-02

Pre-check: Arducopter 4.5.6 + OpenIPC SSC338Q+IMX415  ==> PC(wfb-ng) 14550 mavlinkv2 works(input/output) fine. 
==> hardware and software configuration is ok for arducopter and OpenIPC

Now, Arducopter 4.5.6 + OpenIPC SSC338Q+IMX415 + Hi3536  ==> OSD doesn't change at all.

I suspect some configuration or VDEC is not properly configured? 

Any idea?

**Comment by MarioFPVdev** [comment]
Please post your vdec.conf
Also make sure you are using the latest firmware for OSD editing.

**Comment by lida2003** [comment]
GS version is master+5f03f03, 2024-03-02, and camera is master+94d0b84, 2024-06-20. 
The above firmware is shipped with boards, it might be version issue. Please checked the config, and let me know if I should reflash latest firmware for test, thanks.


```
root@openipc-hi3536dv100:~# cat /etc/wfb.conf
### unit: drone or gs
unit=gs

wlan=wlan0
region=00
### By default used channel number, but, you may set freq instead. For ex: 2387M
channel=161
frequency=
txpower=20
driver_txpower_override=20
stream=0
link_id=7669206
udp_addr=127.0.0.1
udp_port=5600
telemetry=true
```

```
root@openipc-hi3536dv100:~# cat /etc/mavlink.conf
[General]
TcpServerPort = 0
DebugLogLevel = error

[UdpEndpoint external_use]
Mode = Server
Address = 0.0.0.0
Port = 14550

[UdpEndpoint vdec]
Mode = Normal
Address = 127.0.0.1
Port = 14750

[UdpEndpoint telemetry_tx]
Group = wfb
Mode = Normal
Address = 127.0.0.1
Port = 14650

[UdpEndpoint telemetry_rx]
Group = wfb
Mode = Server
Address = 127.0.0.1
Port = 14651
```

```
# cat /etc/vdec.conf
### Port for video rx (default: 5000)

port=5600

### Codec: h264 or h265 (default: h264)

codec=h265

### Incoming data format: stream or frame (default: stream)

format=frame

### Screen output mode:
# 720p60       - 1280 x 720  @ 60 fps
# 1080p60      - 1920 x 1080 @ 60 fps
# 1024x768x60  - 1024 x 768  @ 60 fps
# 1366x768x60  - 1366 x 768  @ 60 fps
# 1280x1024x60 - 1280 x 1024 @ 60 fps
# 1600x1200x60 - 1600 x 1200 @ 60 fps
# 2560x1440x30 - 2560 x 1440 @ 30 fps

mode=1920x1080x60

### Mavlink port for telemetry (default: 14750)

mavlink_port=14750

### Osd: none, simple or custom for use own lvgl based osd (custom osd binary need to be upload to /usr/bin directory) (default:                                         simple)

osd=simple

### Records archive (Mount ssd, set up full path to records archive, file names generated automatically. example: /mnt/sda1/reco                                        rder)

records=
#records=/mnt/sda1/recorder

### Extra param (write in one line split by space):

#    --ar [mode]        - Aspect ratio mode               (Default: keep)
#      keep             - Keep stream aspect ratio
#      stretch          - Stretch to output resolution
#      manual           - Manual image size definition

#    --ar-bg-r [Value]  - Fill color red component      (Default: 0)
#    --ar-bg-g [Value]  - Fill color green component    (Default: 0)
#    --ar-bg-b [Value]  - Fill color blue component     (Default: 0)

#    --ar-x [Value]     - Image position X
#    --ar-y [Value]     - Image position Y
#    --ar-w [Value]     - Image width
#    --ar-h [Value]     - Image height

#    --bg-r [Value]     - Background color red      (Default: 0)
#    --bg-g [Value]     - Background color green    (Default: 96)
#    --bg-b [Value]     - Background color blue     (Default: 0)

extra="--bg-r 30 --bg-g 0 --bg-b 30"
```

**Comment by MarioFPVdev** [comment]
You have an old version of our firmware. Please upgrade.

**Comment by lida2003** [comment]
Now I have did sysupgrade, both camera and gs3536.
- hi3536dv100: master+8d995d7, 2024-10-19
- ssc30kq: master+8d995d7, 2024-10-19

The mav route port 14550 is working (in/out). But the OSD is gone, even icons were not there.

**Comment by lida2003** [comment]
OK, I add osd elements in configuration: `osd_elements="-osd_ele1x 910 -osd_ele1y 350 -osd_ele2x 240 -osd_ele2y 350 -osd_ele3x 910 -osd_ele3y 380 -osd_ele4x 40 -osd_ele4y 680 -osd_ele5x 40 -osd_ele5y 650 -osd_ele6x 40 -osd_ele6y 620 -osd_ele7x 40 -osd_ele7y 590 -osd_ele8x 1150 -osd_ele8y 680 -osd_ele9x 1150 -osd_ele9y 590 -osd_ele10x 1050 -osd_ele10y 620 -osd_ele11x 1050 -osd_ele11y 650 -osd_ele12x 350 -osd_ele12y 680 -osd_ele13x 600 -osd_ele13y 680 -osd_ele14x 1100 -osd_ele14y 20 -osd_ele15x 550 -osd_ele15y 30 -osd_ele16x 200 -osd_ele16y 30 -osd_ele17x 1050 -osd_ele17y 560 -osd_ele18x 2 -osd_ele18y 2"`

And icon shows, but still no value updates.

**Comment by lida2003** [comment]
@MarioFPVdev 

It has something to do with https://discuss.ardupilot.org/t/why-there-is-no-srx-ext-stat-x-4/125193
I tried Kakute F7  4.5.7 UART1, setting porper value, then it works (horizontal line moves)

![图片](https://github.com/user-attachments/assets/0a4f161d-7716-4a32-92bd-71b7f96f0d71)


And previously, I'm using [Aocoda-RC, UART8](https://ardupilot.org/copter/docs/common-aocoda-h743dual.html), and there is no SR8_BLABLA..... for parameter settings.

Is it possible to add those message interval settings in the code?

```
    // Set intervals for specific MAVLink messages
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_RAW_IMU, 200000);           // 5 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_SYS_STATUS, 1000000);      // 1 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_BATTERY_STATUS, 1000000);  // 1 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_RC_CHANNELS_RAW, 500000);  // 2 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_GPS_RAW_INT, 200000);      // 5 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_VFR_HUD, 200000);          // 5 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_GLOBAL_POSITION_INT, 100000);  // 10 Hz
    set_message_interval(system_id, component_id, target_system, target_component, MAVLINK_MSG_ID_ATTITUDE, 100000);         // 10 Hz
```

**Comment by lida2003** [comment]
OK, it's clear now.

Ardupilot, please consulting https://discuss.ardupilot.org/t/why-there-is-no-srx-ext-stat-x-4/125193

![图片](https://github.com/user-attachments/assets/720c1e8c-1f0b-4010-8b07-6a326546cc34)
