### ISSUE TITLE
About NAL fragmentation.

### ISSUE THREAD

**Issue by Lance0724** [OpenIPC/silicon_research#6]
By modifying the wfb-ng code to remove NAL fragmentation before forwarding the video stream, 
Can I use a third party to decode the video? (e.g. QOpenHD, fpv_vr)

**Comment by iHardRock** [comment]
You may use third party applications with venc running in RTP mode and h264 encoder. For h265 venc should be fixed.

**Comment by Lance0724** [comment]
> You may use third party applications with venc running in RTP mode and h264 encoder. For h265 venc should be fixed.
Use the following parameter?
-m rtp  
Thanks .
